-- SPDX-License-Identifier: MIT AND Apache-2.0
-- Copyright 2026 Sean Brandt
-- Current business schema generated by native PostgreSQL pg_dump.

-- +goose Up
-- +goose StatementBegin
--
-- PostgreSQL database dump
--


-- Dumped from database version 18.6 (Debian 18.6-1.pgdg12+2)
-- Dumped by pg_dump version 18.6 (Debian 18.6-1.pgdg12+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: vector; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA public;


--
-- Name: EXTENSION vector; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION vector IS 'vector data type and ivfflat and hnsw access methods';


--
-- Name: advance_spec_scope_revision(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.advance_spec_scope_revision() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    NEW.scope_revision := OLD.scope_revision;
    IF spec_scope_contract(OLD.intent, OLD.shape_output, OLD.specify_output)
        IS DISTINCT FROM spec_scope_contract(NEW.intent, NEW.shape_output, NEW.specify_output) THEN
        NEW.scope_revision := OLD.scope_revision + 1;
    END IF;
    RETURN NEW;
END;
$$;


--
-- Name: record_dependency_change(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.record_dependency_change() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    IF TG_OP = 'UPDATE' THEN
        IF ROW(OLD.project_slug, OLD.from_slug, OLD.to_slug, OLD.edge_type)
            IS NOT DISTINCT FROM ROW(NEW.project_slug, NEW.from_slug, NEW.to_slug, NEW.edge_type) THEN
            RETURN NULL;
        END IF;
    END IF;

    IF TG_OP IN ('DELETE', 'UPDATE') THEN
        IF OLD.edge_type IN ('DEPENDS_ON', 'BLOCKS') THEN
            INSERT INTO dependency_changes (project_slug, dependent_slug, prerequisite_slug, edge_type, operation)
            VALUES (OLD.project_slug,
                CASE WHEN OLD.edge_type = 'DEPENDS_ON' THEN OLD.from_slug ELSE OLD.to_slug END,
                CASE WHEN OLD.edge_type = 'DEPENDS_ON' THEN OLD.to_slug ELSE OLD.from_slug END,
                OLD.edge_type, 'DELETE');
        END IF;
    END IF;

    IF TG_OP IN ('INSERT', 'UPDATE') THEN
        IF NEW.edge_type IN ('DEPENDS_ON', 'BLOCKS') THEN
            INSERT INTO dependency_changes (project_slug, dependent_slug, prerequisite_slug, edge_type, operation)
            VALUES (NEW.project_slug,
                CASE WHEN NEW.edge_type = 'DEPENDS_ON' THEN NEW.from_slug ELSE NEW.to_slug END,
                CASE WHEN NEW.edge_type = 'DEPENDS_ON' THEN NEW.to_slug ELSE NEW.from_slug END,
                NEW.edge_type, 'INSERT');
        END IF;
    END IF;
    RETURN NULL;
END;
$$;


--
-- Name: spec_scope_contract(text, jsonb, jsonb); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.spec_scope_contract(intent text, shape jsonb, specify jsonb) RETURNS jsonb
    LANGUAGE sql IMMUTABLE
    AS $$
    SELECT jsonb_build_object(
        'intent', intent,
        'shape', COALESCE((SELECT jsonb_object_agg(key, value)
            FROM jsonb_each(COALESCE(NULLIF(shape, 'null'::jsonb), '{}'::jsonb))
            WHERE value NOT IN ('null'::jsonb, '""'::jsonb, '[]'::jsonb, '{}'::jsonb)), '{}'::jsonb),
        'specify', COALESCE((SELECT jsonb_object_agg(key, value)
            FROM jsonb_each(COALESCE(NULLIF(specify, 'null'::jsonb), '{}'::jsonb))
            WHERE value NOT IN ('null'::jsonb, '""'::jsonb, '[]'::jsonb, '{}'::jsonb)), '{}'::jsonb)
    );
$$;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: acceptances; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.acceptances (
    id text NOT NULL,
    project_slug text NOT NULL,
    delivery_id text NOT NULL,
    requirements_fingerprint text DEFAULT ''::text NOT NULL,
    verdict text DEFAULT 'accepted'::text NOT NULL,
    approver text DEFAULT ''::text NOT NULL,
    conditions jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: changelog_entries; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.changelog_entries (
    id text NOT NULL,
    spec_slug text NOT NULL,
    project_slug text NOT NULL,
    version integer NOT NULL,
    stage text DEFAULT ''::text NOT NULL,
    content_hash text DEFAULT ''::text NOT NULL,
    checkpoint boolean DEFAULT false NOT NULL,
    summary text DEFAULT ''::text NOT NULL,
    reason text DEFAULT ''::text NOT NULL,
    changes jsonb DEFAULT '[]'::jsonb NOT NULL,
    date timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: claims; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.claims (
    spec_slug text NOT NULL,
    project_slug text NOT NULL,
    agent text NOT NULL,
    lease_expires timestamp with time zone NOT NULL,
    claimed_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: constitutions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.constitutions (
    id text NOT NULL,
    project_slug text NOT NULL,
    layer text DEFAULT ''::text NOT NULL,
    name text DEFAULT ''::text NOT NULL,
    version integer DEFAULT 1 NOT NULL,
    data jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    source_url text DEFAULT ''::text NOT NULL,
    source_hash text DEFAULT ''::text NOT NULL
);


--
-- Name: context_packages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.context_packages (
    id text NOT NULL,
    project_slug text NOT NULL,
    task_spec_slug text DEFAULT ''::text NOT NULL,
    body jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: conversation_logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.conversation_logs (
    id text NOT NULL,
    spec_slug text NOT NULL,
    project_slug text NOT NULL,
    stage text DEFAULT ''::text NOT NULL,
    version integer DEFAULT 0 NOT NULL,
    is_amend boolean DEFAULT false NOT NULL,
    exchanges jsonb DEFAULT '[]'::jsonb NOT NULL,
    exchange_count integer DEFAULT 0 NOT NULL,
    date timestamp with time zone DEFAULT now() NOT NULL,
    posture text DEFAULT ''::text NOT NULL
);


--
-- Name: decisions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.decisions (
    slug text NOT NULL,
    project_slug text NOT NULL,
    title text DEFAULT ''::text NOT NULL,
    status text DEFAULT 'proposed'::text NOT NULL,
    body text DEFAULT ''::text NOT NULL,
    rationale text DEFAULT ''::text NOT NULL,
    question text DEFAULT ''::text NOT NULL,
    superseded_by text DEFAULT ''::text NOT NULL,
    confidence text DEFAULT ''::text NOT NULL,
    scope text DEFAULT ''::text NOT NULL,
    origin_spec text DEFAULT ''::text NOT NULL,
    origin_stage text DEFAULT ''::text NOT NULL,
    tags text[] DEFAULT '{}'::text[] NOT NULL,
    rejected_alternatives jsonb,
    content_hash text DEFAULT ''::text NOT NULL,
    version integer DEFAULT 1 NOT NULL,
    embedding public.vector(3072),
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    id text DEFAULT ''::text NOT NULL
);


--
-- Name: deliveries; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.deliveries (
    id text NOT NULL,
    project_slug text NOT NULL,
    run_binding_id text NOT NULL,
    snapshot jsonb NOT NULL,
    submitted_by text DEFAULT ''::text NOT NULL,
    submitted_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: dependency_changes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.dependency_changes (
    id bigint NOT NULL,
    project_slug text NOT NULL,
    dependent_slug text NOT NULL,
    prerequisite_slug text NOT NULL,
    edge_type text NOT NULL,
    operation text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT dependency_changes_edge_type_check CHECK ((edge_type = ANY (ARRAY['DEPENDS_ON'::text, 'BLOCKS'::text]))),
    CONSTRAINT dependency_changes_operation_check CHECK ((operation = ANY (ARRAY['INSERT'::text, 'DELETE'::text])))
);


--
-- Name: dependency_changes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.dependency_changes ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.dependency_changes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: dependency_edits; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.dependency_edits (
    id text NOT NULL,
    project_slug text NOT NULL,
    dependent_slug text NOT NULL,
    prerequisite_slug text NOT NULL,
    actor text NOT NULL,
    reason text NOT NULL,
    idempotency_key text NOT NULL,
    expected_version integer NOT NULL,
    expected_prerequisite_version integer NOT NULL,
    expected_revision bigint NOT NULL,
    result_revision bigint NOT NULL,
    changed boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    operation text DEFAULT 'add'::text NOT NULL,
    CONSTRAINT dependency_edits_operation_check CHECK ((operation = ANY (ARRAY['add'::text, 'remove'::text])))
);


--
-- Name: edges; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.edges (
    from_slug text NOT NULL,
    to_slug text NOT NULL,
    edge_type text NOT NULL,
    project_slug text NOT NULL,
    content_hash_at_link text DEFAULT ''::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: evidence; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.evidence (
    id text NOT NULL,
    record_order bigint GENERATED ALWAYS AS IDENTITY UNIQUE,
    project_slug text NOT NULL,
    delivery_id text NOT NULL,
    kind text DEFAULT ''::text NOT NULL,
    command text DEFAULT ''::text NOT NULL,
    exit_code bigint,
    result jsonb NOT NULL,
    artifact_refs jsonb DEFAULT '[]'::jsonb NOT NULL,
    environment jsonb DEFAULT '{}'::jsonb NOT NULL,
    verifier text DEFAULT ''::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE INDEX evidence_test_report_order ON public.evidence(project_slug,delivery_id,record_order DESC) WHERE kind='test_report';


--
-- Name: execution_events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.execution_events (
    id text NOT NULL,
    spec_slug text NOT NULL,
    project_slug text NOT NULL,
    agent text DEFAULT ''::text NOT NULL,
    event_type text NOT NULL,
    message text DEFAULT ''::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: findings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.findings (
    id text NOT NULL,
    spec_slug text NOT NULL,
    project_slug text NOT NULL,
    pass_type text NOT NULL,
    severity text DEFAULT ''::text NOT NULL,
    summary text DEFAULT ''::text NOT NULL,
    detail text DEFAULT ''::text NOT NULL,
    constraint_ text DEFAULT ''::text NOT NULL,
    resolution text DEFAULT ''::text NOT NULL,
    version integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: mail_bindings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.mail_bindings (
    project_slug text NOT NULL,
    id text NOT NULL,
    grant_id text NOT NULL,
    environment_id text NOT NULL,
    thread_id text NOT NULL,
    provider_session_id text NOT NULL,
    provider_instance_id text NOT NULL,
    run_id text NOT NULL,
    approved_by text NOT NULL,
    approved_at timestamp with time zone NOT NULL,
    revoked_by text,
    revoked_at timestamp with time zone,
    CONSTRAINT mail_bindings_check CHECK (((revoked_by IS NULL) = (revoked_at IS NULL)))
);


--
-- Name: mail_grants; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.mail_grants (
    project_slug text NOT NULL,
    id text NOT NULL,
    environment_id text NOT NULL,
    bridge_subject text NOT NULL,
    granted_by text NOT NULL,
    granted_at timestamp with time zone NOT NULL,
    revoked_by text,
    revoked_at timestamp with time zone,
    CONSTRAINT mail_grants_bridge_subject_check CHECK ((bridge_subject ~~ 'apikey:_%'::text)),
    CONSTRAINT mail_grants_check CHECK (((revoked_by IS NULL) = (revoked_at IS NULL)))
);


--
-- Name: mail_messages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.mail_messages (
    project_slug text NOT NULL,
    id text NOT NULL,
    thread_id text NOT NULL,
    sender_run text NOT NULL,
    idempotency_key text NOT NULL,
    requested_thread_id text NOT NULL,
    handoff_to_run text,
    body text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT mail_messages_body_check CHECK (((octet_length(body) >= 1) AND (octet_length(body) <= 65536))),
    CONSTRAINT mail_messages_check CHECK (((requested_thread_id = ''::text) OR (requested_thread_id = thread_id))),
    CONSTRAINT mail_messages_handoff_check CHECK ((handoff_to_run IS NULL OR (handoff_to_run <> sender_run AND requested_thread_id = thread_id))),
    CONSTRAINT mail_messages_idempotency_key_check CHECK (((octet_length(idempotency_key) >= 1) AND (octet_length(idempotency_key) <= 256)))
);


--
-- Name: mail_recipients; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.mail_recipients (
    project_slug text NOT NULL,
    message_id text NOT NULL,
    recipient_run text NOT NULL,
    read_at timestamp with time zone,
    acknowledged_at timestamp with time zone
);


--
-- Name: mail_references; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.mail_references (
    project_slug text NOT NULL,
    message_id text NOT NULL,
    source_message_id text NOT NULL,
    kind text NOT NULL,
    CONSTRAINT mail_references_check CHECK ((message_id <> source_message_id)),
    CONSTRAINT mail_references_kind_check CHECK ((kind = ANY (ARRAY['reply'::text, 'forward'::text, 'context'::text])))
);


--
-- Name: mail_threads; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.mail_threads (
    project_slug text NOT NULL,
    id text NOT NULL,
    task_slug text NOT NULL,
    opened_by_run text NOT NULL,
    owner_run text NOT NULL,
    subject text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    closed_at timestamp with time zone,
    closed_by_run text,
    closure_note text,
    CONSTRAINT mail_threads_check CHECK ((((closed_at IS NULL) AND (closed_by_run IS NULL) AND (closure_note IS NULL)) OR ((closed_at IS NOT NULL) AND (closed_by_run IS NOT NULL) AND (closed_by_run = owner_run) AND (closure_note IS NOT NULL) AND ((octet_length(closure_note) >= 1) AND (octet_length(closure_note) <= 65536))))),
    CONSTRAINT mail_threads_subject_check CHECK (((octet_length(subject) >= 1) AND (octet_length(subject) <= 512)))
);


--
-- Name: manual_completions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.manual_completions (
    id text NOT NULL,
    project_slug text NOT NULL,
    spec_slug text NOT NULL,
    actor text NOT NULL,
    source_version integer NOT NULL,
    result_version integer NOT NULL,
    note text DEFAULT ''::text NOT NULL,
    idempotency_key text NOT NULL,
    created_at timestamp with time zone NOT NULL
);


--
-- Name: preparation_aborts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.preparation_aborts (
    project_slug text NOT NULL,
    idempotency_key text NOT NULL,
    task_slug text NOT NULL,
    workspace text NOT NULL,
    dispatch_target jsonb NOT NULL,
    actor text NOT NULL,
    note text NOT NULL,
    run_id text,
    created_at timestamp with time zone NOT NULL
);


--
-- Name: projects; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.projects (
    slug text NOT NULL,
    sync_adapters text[] DEFAULT '{}'::text[] NOT NULL,
    github_repo text DEFAULT ''::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    managed boolean DEFAULT false NOT NULL
);


--
-- Name: run_bindings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.run_bindings (
    id text NOT NULL,
    project_slug text NOT NULL,
    task_spec_slug text DEFAULT ''::text NOT NULL,
    package_id text DEFAULT ''::text NOT NULL,
    generation bigint DEFAULT 1 NOT NULL,
    thread_ref text DEFAULT ''::text NOT NULL,
    workspace text DEFAULT ''::text NOT NULL,
    state text DEFAULT 'prepared'::text NOT NULL,
    lease_until timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    environment_id text DEFAULT ''::text NOT NULL,
    executor_kind text DEFAULT 'agent'::text NOT NULL CHECK (executor_kind IN ('agent','program')),
    CHECK (executor_kind<>'program' OR thread_ref='')
);


--
-- Name: run_dispatches; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.run_dispatches (
    id text NOT NULL,
    project_slug text NOT NULL,
    task_slug text NOT NULL,
    run_id text NOT NULL,
    package_id text NOT NULL,
    actor text NOT NULL,
    authorized_at timestamp with time zone NOT NULL,
    released_at timestamp with time zone,
    release_actor text,
    release_kind text,
    release_note text,
    stop_confirmed_at timestamp with time zone,
    stop_actor text,
    stop_note text,
    stop_program_attempt_id text,
    CONSTRAINT run_dispatches_stop_check CHECK (((stop_confirmed_at IS NULL AND stop_actor IS NULL AND stop_note IS NULL AND stop_program_attempt_id IS NULL)
        OR (stop_confirmed_at IS NOT NULL AND stop_actor IS NOT NULL AND stop_note IS NOT NULL AND released_at IS NOT NULL))),
    CONSTRAINT run_dispatches_check CHECK ((((released_at IS NULL) AND (release_actor IS NULL) AND (release_kind IS NULL) AND (release_note IS NULL)) OR ((released_at IS NOT NULL) AND (release_actor IS NOT NULL) AND (release_kind IS NOT NULL) AND (release_note IS NOT NULL)))),
    CONSTRAINT run_dispatches_release_kind_check CHECK ((release_kind = ANY (ARRAY['stopped_writing'::text, 'isolated_workspace'::text])))
);


--
-- Name: program_attempts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.program_attempts (
    id text NOT NULL,
    project_slug text NOT NULL,
    run_id text NOT NULL,
    admission_id text NOT NULL,
    ordinal integer NOT NULL CHECK (ordinal > 0),
    granted_at timestamp with time zone NOT NULL,
    predecessor_id text,
    consumed_judgment_id text,
    result jsonb CHECK (result IS NULL OR jsonb_typeof(result)='object')
);

CREATE TABLE public.program_loop_events (
    sequence bigint GENERATED ALWAYS AS IDENTITY UNIQUE,
    id text PRIMARY KEY,
    project_slug text NOT NULL,
    run_id text NOT NULL,
    attempt_id text,
    kind text NOT NULL CHECK (kind IN ('condition','stop')),
    value text CHECK (value IN ('true','false','unknown')),
    actor_user_id text NOT NULL,
    actor_run_id text,
    reason text NOT NULL,
    recorded_at timestamp with time zone NOT NULL,
    predecessor_id text REFERENCES public.program_loop_events(id),
    CHECK ((kind='condition' AND attempt_id IS NOT NULL AND value IS NOT NULL) OR (kind='stop' AND value IS NULL))
);

CREATE INDEX program_loop_events_run ON public.program_loop_events(project_slug,run_id,sequence);
CREATE UNIQUE INDEX program_loop_events_condition_successor ON public.program_loop_events
 (project_slug,run_id,attempt_id,predecessor_id) NULLS NOT DISTINCT WHERE kind='condition';

ALTER TABLE public.program_attempts ADD CONSTRAINT program_attempts_predecessor_unique UNIQUE(project_slug,run_id,predecessor_id);


--
-- Name: run_preparation_cancellations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.run_preparation_cancellations (
    run_id text NOT NULL,
    project_slug text NOT NULL,
    package_id text NOT NULL,
    actor text NOT NULL,
    note text NOT NULL,
    cancelled_at timestamp with time zone NOT NULL,
    raw_handoff jsonb
);


--
-- Name: run_preparations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.run_preparations (
    project_slug text NOT NULL,
    idempotency_key text NOT NULL,
    actor text NOT NULL,
    task_slug text NOT NULL,
    workspace text NOT NULL,
    dispatch_target jsonb,
    run_id text NOT NULL,
    created_at timestamp with time zone NOT NULL
);


--
-- Name: scope_revisions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.scope_revisions (
    id text NOT NULL,
    project_slug text NOT NULL,
    scope text NOT NULL,
    version bigint DEFAULT 1 NOT NULL,
    note text DEFAULT ''::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: slices; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.slices (
    slug text NOT NULL,
    project_slug text NOT NULL,
    parent_slug text NOT NULL,
    slice_id text NOT NULL,
    intent text DEFAULT ''::text NOT NULL,
    status text DEFAULT 'open'::text NOT NULL,
    assigned_to text DEFAULT ''::text NOT NULL,
    verify text[] DEFAULT '{}'::text[] NOT NULL,
    touches text[] DEFAULT '{}'::text[] NOT NULL,
    depends_on text[] DEFAULT '{}'::text[] NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: specs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.specs (
    slug text NOT NULL,
    project_slug text NOT NULL,
    intent text DEFAULT ''::text NOT NULL,
    stage text DEFAULT 'spark'::text NOT NULL,
    priority text DEFAULT ''::text NOT NULL,
    complexity text DEFAULT ''::text NOT NULL,
    notes text DEFAULT ''::text NOT NULL,
    content_hash text DEFAULT ''::text NOT NULL,
    superseded_by text DEFAULT ''::text NOT NULL,
    supersedes text DEFAULT ''::text NOT NULL,
    version integer DEFAULT 1 NOT NULL,
    spark_output jsonb,
    shape_output jsonb,
    specify_output jsonb,
    decompose_output jsonb,
    safety_flags jsonb,
    embedding public.vector(3072),
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    id text DEFAULT ''::text NOT NULL,
    provenance_type text DEFAULT 'authored'::text NOT NULL,
    provenance_detail jsonb DEFAULT '{"data": null, "type": "authored"}'::jsonb NOT NULL,
    role text DEFAULT 'work'::text NOT NULL,
    scope_revision bigint DEFAULT 1 NOT NULL,
    field_source_refs jsonb DEFAULT '{}'::jsonb NOT NULL,
    human_owner_user_id text,
    CONSTRAINT specs_role_check CHECK ((role = ANY (ARRAY['work'::text, 'summary'::text]))),
    CONSTRAINT specs_scope_revision_check CHECK ((scope_revision > 0))
);

CREATE TABLE public.node_ownership_operations (
    id text PRIMARY KEY,
    project_slug text NOT NULL,
    task_slug text NOT NULL,
    idempotency_key text NOT NULL,
    action text NOT NULL CHECK (action IN ('take','return')),
    status text NOT NULL CHECK (status IN ('pending','committed','cancelled')),
    before_owner_user_id text,
    after_owner_user_id text,
    from_version integer NOT NULL,
    to_version integer,
    actor_user_id text NOT NULL,
    reason text NOT NULL,
    dispatches jsonb NOT NULL DEFAULT '[]'::jsonb,
    preparations jsonb NOT NULL DEFAULT '[]'::jsonb,
    handoffs jsonb NOT NULL DEFAULT '[]'::jsonb,
    prepared_handoffs jsonb NOT NULL DEFAULT '[]'::jsonb,
    frozen_claim jsonb,
    claim_handoff jsonb,
    created_at timestamptz NOT NULL,
    finished_at timestamptz,
    cancel_actor_user_id text,
    cancel_reason text,
    UNIQUE(project_slug,idempotency_key),
    CHECK (jsonb_typeof(dispatches)='array' AND jsonb_typeof(preparations)='array' AND jsonb_typeof(handoffs)='array' AND jsonb_typeof(prepared_handoffs)='array'
        AND (frozen_claim IS NULL OR jsonb_typeof(frozen_claim)='object') AND (claim_handoff IS NULL OR jsonb_typeof(claim_handoff)='object')),
    CHECK ((status='pending' AND finished_at IS NULL AND to_version IS NULL AND cancel_actor_user_id IS NULL AND cancel_reason IS NULL)
        OR (status='committed' AND finished_at IS NOT NULL AND to_version IS NOT NULL AND cancel_actor_user_id IS NULL AND cancel_reason IS NULL)
        OR (status='cancelled' AND finished_at IS NOT NULL AND to_version IS NULL AND cancel_actor_user_id IS NOT NULL AND cancel_reason IS NOT NULL))
);
CREATE UNIQUE INDEX node_ownership_one_pending ON public.node_ownership_operations(project_slug,task_slug) WHERE status='pending';
CREATE INDEX node_ownership_history ON public.node_ownership_operations(project_slug,task_slug,created_at DESC,id DESC);


--
-- Name: subdivision_children; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.subdivision_children (
    operation_id text NOT NULL,
    project_slug text NOT NULL,
    child_slug text NOT NULL,
    child_id text NOT NULL
);


--
-- Name: subdivisions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.subdivisions (
    id text NOT NULL,
    project_slug text NOT NULL,
    parent_slug text NOT NULL,
    actor text NOT NULL,
    reason text NOT NULL,
    source_version integer NOT NULL,
    result_version integer NOT NULL,
    created_at timestamp with time zone NOT NULL
);


--
-- Name: sync_mappings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sync_mappings (
    spec_slug text NOT NULL,
    project_slug text NOT NULL,
    adapter text NOT NULL,
    external_id text DEFAULT ''::text NOT NULL,
    state text DEFAULT 'pending'::text NOT NULL,
    error_message text DEFAULT ''::text NOT NULL,
    last_sync timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: acceptances acceptances_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.acceptances
    ADD CONSTRAINT acceptances_pkey PRIMARY KEY (id);


--
-- Name: changelog_entries changelog_entries_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.changelog_entries
    ADD CONSTRAINT changelog_entries_pkey PRIMARY KEY (project_slug, id);


--
-- Name: claims claims_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.claims
    ADD CONSTRAINT claims_pkey PRIMARY KEY (project_slug, spec_slug);


--
-- Name: constitutions constitutions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.constitutions
    ADD CONSTRAINT constitutions_pkey PRIMARY KEY (project_slug, id);


--
-- Name: context_packages context_packages_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.context_packages
    ADD CONSTRAINT context_packages_pkey PRIMARY KEY (id);


--
-- Name: conversation_logs conversation_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.conversation_logs
    ADD CONSTRAINT conversation_logs_pkey PRIMARY KEY (project_slug, id);


--
-- Name: decisions decisions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.decisions
    ADD CONSTRAINT decisions_pkey PRIMARY KEY (project_slug, slug);


--
-- Name: deliveries deliveries_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.deliveries
    ADD CONSTRAINT deliveries_pkey PRIMARY KEY (id);


--
-- Name: dependency_changes dependency_changes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dependency_changes
    ADD CONSTRAINT dependency_changes_pkey PRIMARY KEY (id);


--
-- Name: dependency_edits dependency_edits_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dependency_edits
    ADD CONSTRAINT dependency_edits_pkey PRIMARY KEY (id);


--
-- Name: dependency_edits dependency_edits_project_slug_idempotency_key_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dependency_edits
    ADD CONSTRAINT dependency_edits_project_slug_idempotency_key_key UNIQUE (project_slug, idempotency_key);


--
-- Name: edges edges_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.edges
    ADD CONSTRAINT edges_pkey PRIMARY KEY (project_slug, from_slug, to_slug, edge_type);


--
-- Name: evidence evidence_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.evidence
    ADD CONSTRAINT evidence_pkey PRIMARY KEY (id);


--
-- Name: execution_events execution_events_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.execution_events
    ADD CONSTRAINT execution_events_pkey PRIMARY KEY (project_slug, id);


--
-- Name: findings findings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.findings
    ADD CONSTRAINT findings_pkey PRIMARY KEY (project_slug, id);


--
-- Name: mail_bindings mail_bindings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mail_bindings
    ADD CONSTRAINT mail_bindings_pkey PRIMARY KEY (project_slug, id);


--
-- Name: mail_grants mail_grants_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mail_grants
    ADD CONSTRAINT mail_grants_pkey PRIMARY KEY (project_slug, id);


--
-- Name: mail_grants mail_grants_project_slug_id_environment_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mail_grants
    ADD CONSTRAINT mail_grants_project_slug_id_environment_id_key UNIQUE (project_slug, id, environment_id);


--
-- Name: mail_messages mail_messages_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mail_messages
    ADD CONSTRAINT mail_messages_pkey PRIMARY KEY (project_slug, id);


--
-- Name: mail_messages mail_messages_project_slug_sender_run_idempotency_key_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mail_messages
    ADD CONSTRAINT mail_messages_project_slug_sender_run_idempotency_key_key UNIQUE (project_slug, sender_run, idempotency_key);


--
-- Name: mail_recipients mail_recipients_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mail_recipients
    ADD CONSTRAINT mail_recipients_pkey PRIMARY KEY (project_slug, message_id, recipient_run);


--
-- Name: mail_references mail_references_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mail_references
    ADD CONSTRAINT mail_references_pkey PRIMARY KEY (project_slug, message_id, source_message_id);


--
-- Name: mail_threads mail_threads_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mail_threads
    ADD CONSTRAINT mail_threads_pkey PRIMARY KEY (project_slug, id);


--
-- Name: manual_completions manual_completions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.manual_completions
    ADD CONSTRAINT manual_completions_pkey PRIMARY KEY (id);


--
-- Name: manual_completions manual_completions_project_slug_spec_slug_idempotency_key_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.manual_completions
    ADD CONSTRAINT manual_completions_project_slug_spec_slug_idempotency_key_key UNIQUE (project_slug, spec_slug, idempotency_key);


--
-- Name: preparation_aborts preparation_aborts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.preparation_aborts
    ADD CONSTRAINT preparation_aborts_pkey PRIMARY KEY (project_slug, idempotency_key);


--
-- Name: projects projects_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.projects
    ADD CONSTRAINT projects_pkey PRIMARY KEY (slug);


--
-- Name: run_bindings run_bindings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.run_bindings
    ADD CONSTRAINT run_bindings_pkey PRIMARY KEY (id);


--
-- Name: run_bindings run_bindings_project_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.run_bindings
    ADD CONSTRAINT run_bindings_project_id_key UNIQUE (project_slug, id);


--
-- Name: run_dispatches run_dispatches_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.run_dispatches
    ADD CONSTRAINT run_dispatches_pkey PRIMARY KEY (id);


--
-- Name: run_dispatches run_dispatches_run_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.run_dispatches
    ADD CONSTRAINT run_dispatches_run_id_key UNIQUE (run_id);

ALTER TABLE ONLY public.run_dispatches
    ADD CONSTRAINT run_dispatches_project_run_id_key UNIQUE (project_slug, run_id, id);

ALTER TABLE ONLY public.program_attempts
    ADD CONSTRAINT program_attempts_pkey PRIMARY KEY (id);

ALTER TABLE public.run_dispatches ADD CONSTRAINT run_dispatches_stop_program_attempt_fk FOREIGN KEY(stop_program_attempt_id) REFERENCES public.program_attempts(id);

ALTER TABLE ONLY public.program_attempts
    ADD CONSTRAINT program_attempts_project_run_ordinal_key UNIQUE (project_slug, run_id, ordinal);


--
-- Name: run_preparation_cancellations run_preparation_cancellations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.run_preparation_cancellations
    ADD CONSTRAINT run_preparation_cancellations_pkey PRIMARY KEY (run_id);


--
-- Name: run_preparations run_preparations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.run_preparations
    ADD CONSTRAINT run_preparations_pkey PRIMARY KEY (project_slug, idempotency_key);


--
-- Name: scope_revisions scope_revisions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scope_revisions
    ADD CONSTRAINT scope_revisions_pkey PRIMARY KEY (id);


--
-- Name: scope_revisions scope_revisions_project_slug_scope_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scope_revisions
    ADD CONSTRAINT scope_revisions_project_slug_scope_key UNIQUE (project_slug, scope);


--
-- Name: slices slices_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.slices
    ADD CONSTRAINT slices_pkey PRIMARY KEY (project_slug, slug);


--
-- Name: specs specs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.specs
    ADD CONSTRAINT specs_pkey PRIMARY KEY (project_slug, slug);


--
-- Name: subdivision_children subdivision_children_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subdivision_children
    ADD CONSTRAINT subdivision_children_pkey PRIMARY KEY (operation_id, child_slug);


--
-- Name: subdivisions subdivisions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subdivisions
    ADD CONSTRAINT subdivisions_pkey PRIMARY KEY (id);


--
-- Name: subdivisions subdivisions_project_slug_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subdivisions
    ADD CONSTRAINT subdivisions_project_slug_id_key UNIQUE (project_slug, id);


--
-- Name: sync_mappings sync_mappings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sync_mappings
    ADD CONSTRAINT sync_mappings_pkey PRIMARY KEY (project_slug, spec_slug, adapter);


--
-- Name: idx_changelog_spec; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_changelog_spec ON public.changelog_entries USING btree (project_slug, spec_slug, version);


--
-- Name: idx_constitutions_project_layer; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_constitutions_project_layer ON public.constitutions USING btree (project_slug, layer);


--
-- Name: idx_conversations_spec; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_conversations_spec ON public.conversation_logs USING btree (project_slug, spec_slug);


--
-- Name: idx_dependency_changes_dependent; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_dependency_changes_dependent ON public.dependency_changes USING btree (project_slug, dependent_slug, id);


--
-- Name: idx_dependency_edits_dependent; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_dependency_edits_dependent ON public.dependency_edits USING btree (project_slug, dependent_slug, created_at DESC, id DESC);


--
-- Name: idx_edges_forward; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_edges_forward ON public.edges USING btree (project_slug, from_slug, edge_type) INCLUDE (to_slug);


--
-- Name: idx_edges_reverse; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_edges_reverse ON public.edges USING btree (project_slug, to_slug, edge_type) INCLUDE (from_slug);


--
-- Name: idx_exec_events_spec; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_exec_events_spec ON public.execution_events USING btree (project_slug, spec_slug, created_at DESC);


--
-- Name: idx_findings_spec; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_findings_spec ON public.findings USING btree (project_slug, spec_slug, pass_type);


--
-- Name: idx_mail_messages_thread; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_mail_messages_thread ON public.mail_messages USING btree (project_slug, thread_id, id);


--
-- Name: idx_mail_recipients_inbox; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_mail_recipients_inbox ON public.mail_recipients USING btree (project_slug, recipient_run, message_id) WHERE (acknowledged_at IS NULL);


--
-- Name: idx_mail_references_reply; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_mail_references_reply ON public.mail_references USING btree (project_slug, message_id) WHERE (kind = 'reply'::text);


--
-- Name: idx_mail_references_source; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_mail_references_source ON public.mail_references USING btree (project_slug, source_message_id);


--
-- Name: idx_run_bindings_task; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_run_bindings_task ON public.run_bindings USING btree (project_slug, task_spec_slug);


--
-- Name: mail_bindings_active_run; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX mail_bindings_active_run ON public.mail_bindings USING btree (project_slug, run_id) WHERE (revoked_at IS NULL);


--
-- Name: mail_bindings_active_thread; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX mail_bindings_active_thread ON public.mail_bindings USING btree (project_slug, environment_id, thread_id) WHERE (revoked_at IS NULL);


--
-- Name: mail_grants_active; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX mail_grants_active ON public.mail_grants USING btree (project_slug, environment_id, bridge_subject) WHERE (revoked_at IS NULL);


--
-- Name: run_dispatches_active_task; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX run_dispatches_active_task ON public.run_dispatches USING btree (project_slug, task_slug) WHERE (released_at IS NULL);


--
-- Name: subdivision_children_spec; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX subdivision_children_spec ON public.subdivision_children USING btree (project_slug, child_slug);


--
-- Name: edges dependency_change_audit; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER dependency_change_audit AFTER INSERT OR DELETE OR UPDATE ON public.edges FOR EACH ROW EXECUTE FUNCTION public.record_dependency_change();


--
-- Name: specs specs_scope_revision; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER specs_scope_revision BEFORE UPDATE ON public.specs FOR EACH ROW EXECUTE FUNCTION public.advance_spec_scope_revision();


--
-- Name: acceptances acceptances_delivery_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.acceptances
    ADD CONSTRAINT acceptances_delivery_id_fkey FOREIGN KEY (delivery_id) REFERENCES public.deliveries(id);


--
-- Name: acceptances acceptances_project_slug_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.acceptances
    ADD CONSTRAINT acceptances_project_slug_fkey FOREIGN KEY (project_slug) REFERENCES public.projects(slug);


--
-- Name: changelog_entries changelog_entries_project_slug_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.changelog_entries
    ADD CONSTRAINT changelog_entries_project_slug_fkey FOREIGN KEY (project_slug) REFERENCES public.projects(slug);


--
-- Name: claims claims_project_slug_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.claims
    ADD CONSTRAINT claims_project_slug_fkey FOREIGN KEY (project_slug) REFERENCES public.projects(slug);


--
-- Name: constitutions constitutions_project_slug_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.constitutions
    ADD CONSTRAINT constitutions_project_slug_fkey FOREIGN KEY (project_slug) REFERENCES public.projects(slug);


--
-- Name: context_packages context_packages_project_slug_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.context_packages
    ADD CONSTRAINT context_packages_project_slug_fkey FOREIGN KEY (project_slug) REFERENCES public.projects(slug);


--
-- Name: conversation_logs conversation_logs_project_slug_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.conversation_logs
    ADD CONSTRAINT conversation_logs_project_slug_fkey FOREIGN KEY (project_slug) REFERENCES public.projects(slug);


--
-- Name: decisions decisions_project_slug_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.decisions
    ADD CONSTRAINT decisions_project_slug_fkey FOREIGN KEY (project_slug) REFERENCES public.projects(slug);


--
-- Name: deliveries deliveries_project_slug_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.deliveries
    ADD CONSTRAINT deliveries_project_slug_fkey FOREIGN KEY (project_slug) REFERENCES public.projects(slug);


--
-- Name: deliveries deliveries_run_binding_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.deliveries
    ADD CONSTRAINT deliveries_run_binding_id_fkey FOREIGN KEY (run_binding_id) REFERENCES public.run_bindings(id);


--
-- Name: dependency_changes dependency_changes_project_slug_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dependency_changes
    ADD CONSTRAINT dependency_changes_project_slug_fkey FOREIGN KEY (project_slug) REFERENCES public.projects(slug);


--
-- Name: dependency_edits dependency_edits_project_slug_dependent_slug_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dependency_edits
    ADD CONSTRAINT dependency_edits_project_slug_dependent_slug_fkey FOREIGN KEY (project_slug, dependent_slug) REFERENCES public.specs(project_slug, slug);


--
-- Name: dependency_edits dependency_edits_project_slug_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dependency_edits
    ADD CONSTRAINT dependency_edits_project_slug_fkey FOREIGN KEY (project_slug) REFERENCES public.projects(slug);


--
-- Name: dependency_edits dependency_edits_project_slug_prerequisite_slug_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dependency_edits
    ADD CONSTRAINT dependency_edits_project_slug_prerequisite_slug_fkey FOREIGN KEY (project_slug, prerequisite_slug) REFERENCES public.specs(project_slug, slug);


--
-- Name: edges edges_project_slug_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.edges
    ADD CONSTRAINT edges_project_slug_fkey FOREIGN KEY (project_slug) REFERENCES public.projects(slug);


--
-- Name: evidence evidence_delivery_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.evidence
    ADD CONSTRAINT evidence_delivery_id_fkey FOREIGN KEY (delivery_id) REFERENCES public.deliveries(id);


--
-- Name: evidence evidence_project_slug_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.evidence
    ADD CONSTRAINT evidence_project_slug_fkey FOREIGN KEY (project_slug) REFERENCES public.projects(slug);


--
-- Name: execution_events execution_events_project_slug_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.execution_events
    ADD CONSTRAINT execution_events_project_slug_fkey FOREIGN KEY (project_slug) REFERENCES public.projects(slug);


--
-- Name: findings findings_project_slug_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.findings
    ADD CONSTRAINT findings_project_slug_fkey FOREIGN KEY (project_slug) REFERENCES public.projects(slug);


--
-- Name: mail_bindings mail_bindings_project_slug_grant_id_environment_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mail_bindings
    ADD CONSTRAINT mail_bindings_project_slug_grant_id_environment_id_fkey FOREIGN KEY (project_slug, grant_id, environment_id) REFERENCES public.mail_grants(project_slug, id, environment_id);


--
-- Name: mail_bindings mail_bindings_project_slug_run_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mail_bindings
    ADD CONSTRAINT mail_bindings_project_slug_run_id_fkey FOREIGN KEY (project_slug, run_id) REFERENCES public.run_bindings(project_slug, id);


--
-- Name: mail_grants mail_grants_project_slug_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mail_grants
    ADD CONSTRAINT mail_grants_project_slug_fkey FOREIGN KEY (project_slug) REFERENCES public.projects(slug);


--
-- Name: mail_messages mail_messages_project_slug_sender_run_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mail_messages
    ADD CONSTRAINT mail_messages_project_slug_sender_run_fkey FOREIGN KEY (project_slug, sender_run) REFERENCES public.run_bindings(project_slug, id);


--
-- Name: mail_messages mail_messages_project_slug_thread_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mail_messages
    ADD CONSTRAINT mail_messages_project_slug_thread_id_fkey FOREIGN KEY (project_slug, thread_id) REFERENCES public.mail_threads(project_slug, id);

ALTER TABLE ONLY public.mail_messages
    ADD CONSTRAINT mail_messages_project_slug_handoff_to_run_fkey FOREIGN KEY (project_slug, handoff_to_run) REFERENCES public.run_bindings(project_slug, id);


--
-- Name: mail_recipients mail_recipients_project_slug_message_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mail_recipients
    ADD CONSTRAINT mail_recipients_project_slug_message_id_fkey FOREIGN KEY (project_slug, message_id) REFERENCES public.mail_messages(project_slug, id);


--
-- Name: mail_recipients mail_recipients_project_slug_recipient_run_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mail_recipients
    ADD CONSTRAINT mail_recipients_project_slug_recipient_run_fkey FOREIGN KEY (project_slug, recipient_run) REFERENCES public.run_bindings(project_slug, id);


--
-- Name: mail_references mail_references_project_slug_message_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mail_references
    ADD CONSTRAINT mail_references_project_slug_message_id_fkey FOREIGN KEY (project_slug, message_id) REFERENCES public.mail_messages(project_slug, id);


--
-- Name: mail_references mail_references_project_slug_source_message_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mail_references
    ADD CONSTRAINT mail_references_project_slug_source_message_id_fkey FOREIGN KEY (project_slug, source_message_id) REFERENCES public.mail_messages(project_slug, id);


--
-- Name: mail_threads mail_threads_project_slug_closed_by_run_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mail_threads
    ADD CONSTRAINT mail_threads_project_slug_closed_by_run_fkey FOREIGN KEY (project_slug, closed_by_run) REFERENCES public.run_bindings(project_slug, id);


--
-- Name: mail_threads mail_threads_project_slug_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mail_threads
    ADD CONSTRAINT mail_threads_project_slug_fkey FOREIGN KEY (project_slug) REFERENCES public.projects(slug);


--
-- Name: mail_threads mail_threads_project_slug_opened_by_run_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mail_threads
    ADD CONSTRAINT mail_threads_project_slug_opened_by_run_fkey FOREIGN KEY (project_slug, opened_by_run) REFERENCES public.run_bindings(project_slug, id);

ALTER TABLE ONLY public.mail_threads
    ADD CONSTRAINT mail_threads_project_slug_owner_run_fkey FOREIGN KEY (project_slug, owner_run) REFERENCES public.run_bindings(project_slug, id);


--
-- Name: mail_threads mail_threads_project_slug_task_slug_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mail_threads
    ADD CONSTRAINT mail_threads_project_slug_task_slug_fkey FOREIGN KEY (project_slug, task_slug) REFERENCES public.specs(project_slug, slug);


--
-- Name: manual_completions manual_completions_project_slug_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.manual_completions
    ADD CONSTRAINT manual_completions_project_slug_fkey FOREIGN KEY (project_slug) REFERENCES public.projects(slug);


--
-- Name: manual_completions manual_completions_project_slug_spec_slug_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.manual_completions
    ADD CONSTRAINT manual_completions_project_slug_spec_slug_fkey FOREIGN KEY (project_slug, spec_slug) REFERENCES public.specs(project_slug, slug);


--
-- Name: preparation_aborts preparation_aborts_project_slug_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.preparation_aborts
    ADD CONSTRAINT preparation_aborts_project_slug_fkey FOREIGN KEY (project_slug) REFERENCES public.projects(slug);


--
-- Name: preparation_aborts preparation_aborts_run_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.preparation_aborts
    ADD CONSTRAINT preparation_aborts_run_id_fkey FOREIGN KEY (run_id) REFERENCES public.run_bindings(id);


--
-- Name: run_bindings run_bindings_project_slug_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.run_bindings
    ADD CONSTRAINT run_bindings_project_slug_fkey FOREIGN KEY (project_slug) REFERENCES public.projects(slug);


--
-- Name: run_dispatches run_dispatches_package_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.run_dispatches
    ADD CONSTRAINT run_dispatches_package_id_fkey FOREIGN KEY (package_id) REFERENCES public.context_packages(id);


--
-- Name: run_dispatches run_dispatches_project_slug_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.run_dispatches
    ADD CONSTRAINT run_dispatches_project_slug_fkey FOREIGN KEY (project_slug) REFERENCES public.projects(slug);


--
-- Name: run_dispatches run_dispatches_run_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.run_dispatches
    ADD CONSTRAINT run_dispatches_run_id_fkey FOREIGN KEY (run_id) REFERENCES public.run_bindings(id);

ALTER TABLE ONLY public.program_attempts
    ADD CONSTRAINT program_attempts_admission_fkey FOREIGN KEY (project_slug, run_id, admission_id) REFERENCES public.run_dispatches(project_slug, run_id, id);

ALTER TABLE public.program_attempts ADD CONSTRAINT program_attempts_predecessor_fk FOREIGN KEY(predecessor_id) REFERENCES public.program_attempts(id);
ALTER TABLE public.program_attempts ADD CONSTRAINT program_attempts_judgment_fk FOREIGN KEY(consumed_judgment_id) REFERENCES public.program_loop_events(id);
ALTER TABLE public.program_loop_events ADD CONSTRAINT program_loop_events_run_fk FOREIGN KEY(run_id) REFERENCES public.run_bindings(id);
ALTER TABLE public.program_loop_events ADD CONSTRAINT program_loop_events_attempt_fk FOREIGN KEY(attempt_id) REFERENCES public.program_attempts(id);


--
-- Name: run_preparation_cancellations run_preparation_cancellations_package_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.run_preparation_cancellations
    ADD CONSTRAINT run_preparation_cancellations_package_id_fkey FOREIGN KEY (package_id) REFERENCES public.context_packages(id);


--
-- Name: run_preparation_cancellations run_preparation_cancellations_project_slug_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.run_preparation_cancellations
    ADD CONSTRAINT run_preparation_cancellations_project_slug_fkey FOREIGN KEY (project_slug) REFERENCES public.projects(slug);


--
-- Name: run_preparation_cancellations run_preparation_cancellations_run_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.run_preparation_cancellations
    ADD CONSTRAINT run_preparation_cancellations_run_id_fkey FOREIGN KEY (run_id) REFERENCES public.run_bindings(id);


--
-- Name: run_preparations run_preparations_project_slug_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.run_preparations
    ADD CONSTRAINT run_preparations_project_slug_fkey FOREIGN KEY (project_slug) REFERENCES public.projects(slug);


--
-- Name: run_preparations run_preparations_run_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.run_preparations
    ADD CONSTRAINT run_preparations_run_id_fkey FOREIGN KEY (run_id) REFERENCES public.run_bindings(id);


--
-- Name: scope_revisions scope_revisions_project_slug_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scope_revisions
    ADD CONSTRAINT scope_revisions_project_slug_fkey FOREIGN KEY (project_slug) REFERENCES public.projects(slug);


--
-- Name: slices slices_project_slug_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.slices
    ADD CONSTRAINT slices_project_slug_fkey FOREIGN KEY (project_slug) REFERENCES public.projects(slug);


--
-- Name: slices slices_project_slug_parent_slug_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.slices
    ADD CONSTRAINT slices_project_slug_parent_slug_fkey FOREIGN KEY (project_slug, parent_slug) REFERENCES public.specs(project_slug, slug);


--
-- Name: specs specs_project_slug_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.specs
    ADD CONSTRAINT specs_project_slug_fkey FOREIGN KEY (project_slug) REFERENCES public.projects(slug);


--
-- Name: subdivision_children subdivision_children_project_slug_child_slug_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subdivision_children
    ADD CONSTRAINT subdivision_children_project_slug_child_slug_fkey FOREIGN KEY (project_slug, child_slug) REFERENCES public.specs(project_slug, slug);


--
-- Name: subdivision_children subdivision_children_project_slug_operation_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subdivision_children
    ADD CONSTRAINT subdivision_children_project_slug_operation_id_fkey FOREIGN KEY (project_slug, operation_id) REFERENCES public.subdivisions(project_slug, id);


--
-- Name: subdivisions subdivisions_project_slug_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subdivisions
    ADD CONSTRAINT subdivisions_project_slug_fkey FOREIGN KEY (project_slug) REFERENCES public.projects(slug);


--
-- Name: subdivisions subdivisions_project_slug_parent_slug_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subdivisions
    ADD CONSTRAINT subdivisions_project_slug_parent_slug_fkey FOREIGN KEY (project_slug, parent_slug) REFERENCES public.specs(project_slug, slug);


--
-- Name: sync_mappings sync_mappings_project_slug_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sync_mappings
    ADD CONSTRAINT sync_mappings_project_slug_fkey FOREIGN KEY (project_slug) REFERENCES public.projects(slug);


--
-- Node judgment revisions are append-only through their storage owner.
-- Current state is the latest revision, including explicit clearance.
--

CREATE TABLE public.node_marks (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    project_slug text NOT NULL REFERENCES public.projects(slug),
    task_slug text NOT NULL,
    kind text NOT NULL,
    value text NOT NULL,
    reason text NOT NULL CHECK (char_length(reason) BETWEEN 1 AND 4000 AND btrim(reason) <> ''),
    actor text NOT NULL CHECK (btrim(actor) <> ''),
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    FOREIGN KEY (project_slug, task_slug) REFERENCES public.specs(project_slug, slug),
    CHECK ((kind = 'risk' AND value IN ('watch', 'high', 'cleared'))
        OR (kind = 'critical' AND value IN ('marked', 'cleared')))
);

CREATE INDEX node_marks_task_history ON public.node_marks (project_slug, task_slug, id DESC);

CREATE TABLE public.node_execution_events (
    id text NOT NULL CHECK (id ~ '^[A-Za-z0-9_-]{1,128}$'),
    event_order bigint GENERATED ALWAYS AS IDENTITY UNIQUE,
    project_slug text NOT NULL REFERENCES public.projects(slug),
    task_slug text NOT NULL,
    kind text NOT NULL CHECK (kind IN ('retry','rework','git_undo')),
    reason text NOT NULL CHECK (btrim(reason)<>'' AND char_length(reason)<=4000),
    actor text NOT NULL CHECK (btrim(actor)<>''),
    previous_run_id text,
    run_id text,
    delivery_id text REFERENCES public.deliveries(id),
    git_undo jsonb,
    recorded_at timestamp with time zone DEFAULT now() NOT NULL,
    PRIMARY KEY (project_slug,id),
    FOREIGN KEY (project_slug,task_slug) REFERENCES public.specs(project_slug,slug),
    FOREIGN KEY (project_slug,previous_run_id) REFERENCES public.run_bindings(project_slug,id),
    FOREIGN KEY (project_slug,run_id) REFERENCES public.run_bindings(project_slug,id),
    CHECK ((kind='retry' AND previous_run_id IS NOT NULL AND delivery_id IS NULL AND git_undo IS NULL)
        OR (kind='rework' AND delivery_id IS NOT NULL AND previous_run_id IS NULL AND run_id IS NULL AND git_undo IS NULL)
        OR (kind='git_undo' AND previous_run_id IS NULL AND delivery_id IS NULL AND run_id IS NOT NULL
            AND git_undo IS NOT NULL AND jsonb_typeof(git_undo)='object'
            AND git_undo ? 'operation' AND git_undo ? 'sourceCommit' AND git_undo ? 'resultCommit'
            AND jsonb_typeof(git_undo->'operation')='string'
            AND jsonb_typeof(git_undo->'sourceCommit')='string'
            AND jsonb_typeof(git_undo->'resultCommit')='string'
            AND git_undo->>'operation' IN ('revert','reset')
            AND git_undo->>'sourceCommit' ~ '^([0-9a-fA-F]{40}|[0-9a-fA-F]{64})$'
            AND git_undo->>'resultCommit' ~ '^([0-9a-fA-F]{40}|[0-9a-fA-F]{64})$'
            AND (git_undo->>'operation'<>'revert' OR lower(git_undo->>'sourceCommit')<>lower(git_undo->>'resultCommit'))))
);
CREATE INDEX node_execution_events_history ON public.node_execution_events(project_slug,task_slug,event_order DESC);

CREATE TABLE public.review_requests (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    project_slug text NOT NULL REFERENCES public.projects(slug),
    task_slug text NOT NULL,
    kind text NOT NULL CHECK (kind IN ('requirements','design')),
    sources jsonb NOT NULL CHECK (jsonb_typeof(sources)='array' AND jsonb_array_length(sources)>0),
    author_responsibility jsonb NOT NULL CHECK (jsonb_typeof(author_responsibility)='object'),
    requirement_decision_ids jsonb NOT NULL DEFAULT '[]' CHECK (jsonb_typeof(requirement_decision_ids)='array'),
    reviewer_run_id text NOT NULL REFERENCES public.run_bindings(id),
    completion_run_id text,
    responsible_user_id text NOT NULL,
    max_review_rounds integer NOT NULL CHECK (max_review_rounds > 0),
    agent_rejections integer DEFAULT 0 NOT NULL CHECK (agent_rejections >= 0),
    human_hold boolean DEFAULT false NOT NULL,
    created_by text NOT NULL,
    assigned_by_run_id text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    decided_at timestamp with time zone,
    FOREIGN KEY (project_slug, task_slug) REFERENCES public.specs(project_slug, slug),
    FOREIGN KEY (project_slug, completion_run_id) REFERENCES public.run_bindings(project_slug,id),
    UNIQUE (project_slug,id)
);

CREATE INDEX review_requests_task ON public.review_requests(project_slug,task_slug,kind,id DESC);

CREATE TABLE public.review_decisions (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    project_slug text NOT NULL,
    request_id bigint NOT NULL,
    verdict text NOT NULL CHECK (verdict IN ('accepted','rejected')),
    basis text NOT NULL CHECK (btrim(basis)<>'' AND char_length(basis)<=4000),
    actor_kind text NOT NULL CHECK (actor_kind IN ('human','agent')),
    actor text NOT NULL,
    reviewer_run_id text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    FOREIGN KEY (project_slug,request_id) REFERENCES public.review_requests(project_slug,id),
    CHECK ((actor_kind='agent' AND reviewer_run_id IS NOT NULL) OR (actor_kind='human' AND reviewer_run_id IS NULL))
);
CREATE INDEX review_decisions_request ON public.review_decisions(project_slug,request_id,id);
CREATE UNIQUE INDEX review_decisions_agent_request ON public.review_decisions(project_slug,request_id) WHERE actor_kind='agent';

ALTER TABLE public.acceptances
    ADD COLUMN actor_kind text NOT NULL DEFAULT '' CHECK (actor_kind IN ('','human','agent')),
    ADD COLUMN reviewer_run_id text,
    ADD COLUMN review_request_id bigint;

CREATE UNIQUE INDEX acceptances_agent_request ON public.acceptances(project_slug,review_request_id) WHERE actor_kind='agent';

CREATE TABLE public.mail_owner_events (
    project_slug text NOT NULL,
    id text NOT NULL,
    thread_id text NOT NULL,
    from_run text NOT NULL,
    to_run text NOT NULL,
    actor_kind text NOT NULL CHECK (actor_kind IN ('human','agent')),
    actor_user_id text NOT NULL CHECK (btrim(actor_user_id)<>''),
    actor_run_id text,
    reason text NOT NULL CHECK (btrim(reason)<>'' AND octet_length(reason)<=65536),
    idempotency_key text NOT NULL CHECK (btrim(idempotency_key)<>'' AND octet_length(idempotency_key)<=256),
    created_at timestamp with time zone NOT NULL,
    PRIMARY KEY (project_slug,id),
    UNIQUE NULLS NOT DISTINCT (project_slug,actor_user_id,actor_run_id,idempotency_key),
    FOREIGN KEY (project_slug,thread_id) REFERENCES public.mail_threads(project_slug,id),
    FOREIGN KEY (project_slug,from_run) REFERENCES public.run_bindings(project_slug,id),
    FOREIGN KEY (project_slug,to_run) REFERENCES public.run_bindings(project_slug,id),
    FOREIGN KEY (project_slug,actor_run_id) REFERENCES public.run_bindings(project_slug,id),
    CHECK (from_run<>to_run),
    CHECK ((actor_kind='human' AND actor_run_id IS NULL) OR (actor_kind='agent' AND actor_run_id IS NOT NULL))
);
CREATE INDEX mail_owner_events_thread ON public.mail_owner_events(project_slug,thread_id,id DESC);

CREATE TABLE public.delivery_test_hooks (
    project_slug text NOT NULL REFERENCES public.projects(slug),
    id text NOT NULL,
    hook_kind text NOT NULL DEFAULT 'delivery_test' CHECK (hook_kind IN ('delivery_test','completion_program')),
    source_run_id text,
    source_task_slug text,
    source_spec_id text,
    source_role text CHECK (source_role IN ('work','summary')),
    requested_fact_kind text CHECK (requested_fact_kind IN ('execution','manual','summary')),
    requested_fact_id text,
    fact_kind text CHECK (fact_kind IN ('execution','manual','summary')),
    fact_id text,
    program_admission_id text REFERENCES public.run_dispatches(id),
    target_run_id text NOT NULL,
    target_package_id text NOT NULL REFERENCES public.context_packages(id),
    commit_sha text CHECK (commit_sha ~ '^([0-9a-fA-F]{40}|[0-9a-fA-F]{64})$'),
    configured_by_run_id text,
    configured_by_user_id text NOT NULL CHECK (btrim(configured_by_user_id)<>''),
    host_consumer_user_id text NOT NULL CHECK (btrim(host_consumer_user_id)<>''),
    idempotency_key text NOT NULL,
    requested_delivery_id text REFERENCES public.deliveries(id),
    delivery_id text REFERENCES public.deliveries(id),
    created_at timestamp with time zone NOT NULL,
    triggered_at timestamp with time zone,
    cancelled_at timestamp with time zone,
    cancelled_by_run_id text,
    cancelled_by_user_id text,
    cancellation_reason text,
    dispatch_status text CHECK (dispatch_status IN ('commandAccepted','rejected','unconfirmed','blocked')),
    dispatch_phase text CHECK (dispatch_phase IN ('create','start')),
    dispatch_detail text,
    dispatch_recorded_at timestamp with time zone,
    retried_at timestamp with time zone,
    retried_by_run_id text,
    retried_by_user_id text,
    PRIMARY KEY (project_slug,id),
    UNIQUE (project_slug,configured_by_run_id,idempotency_key),
    FOREIGN KEY (project_slug,source_task_slug) REFERENCES public.specs(project_slug,slug),
    FOREIGN KEY (project_slug,source_run_id) REFERENCES public.run_bindings(project_slug,id),
    FOREIGN KEY (project_slug,target_run_id) REFERENCES public.run_bindings(project_slug,id),
    FOREIGN KEY (project_slug,configured_by_run_id) REFERENCES public.run_bindings(project_slug,id),
    FOREIGN KEY (project_slug,cancelled_by_run_id) REFERENCES public.run_bindings(project_slug,id),
    FOREIGN KEY (project_slug,retried_by_run_id) REFERENCES public.run_bindings(project_slug,id),
    CHECK (source_run_id<>target_run_id),
    CHECK ((hook_kind='delivery_test' AND source_run_id IS NOT NULL AND commit_sha IS NOT NULL
        AND source_task_slug IS NULL AND source_spec_id IS NULL AND source_role IS NULL
        AND requested_fact_kind IS NULL AND requested_fact_id IS NULL AND fact_kind IS NULL AND fact_id IS NULL AND program_admission_id IS NULL
        AND ((delivery_id IS NULL)=(triggered_at IS NULL))) OR
        (hook_kind='completion_program' AND source_run_id IS NULL AND commit_sha IS NULL
        AND source_task_slug IS NOT NULL AND source_spec_id IS NOT NULL AND source_role IS NOT NULL
        AND configured_by_run_id IS NULL AND requested_delivery_id IS NULL AND delivery_id IS NULL
        AND ((fact_id IS NULL)=(triggered_at IS NULL)) AND ((fact_id IS NULL)=(fact_kind IS NULL))
        AND ((requested_fact_id IS NULL)=(requested_fact_kind IS NULL))
        AND (requested_fact_id IS NULL OR (fact_id IS NOT NULL AND requested_fact_id=fact_id AND requested_fact_kind=fact_kind))
        AND (program_admission_id IS NULL OR fact_id IS NOT NULL)
        AND (fact_kind IS NULL OR (source_role='summary' AND fact_kind='summary') OR (source_role='work' AND fact_kind IN ('execution','manual')))
        AND (dispatch_status IS NULL OR dispatch_status IN ('blocked','unconfirmed')) AND dispatch_phase IS NULL)),
    CHECK ((dispatch_status IS NULL AND dispatch_phase IS NULL AND dispatch_detail IS NULL AND dispatch_recorded_at IS NULL)
        OR (dispatch_status IS NOT NULL AND dispatch_recorded_at IS NOT NULL AND (delivery_id IS NOT NULL OR fact_id IS NOT NULL)
            AND (dispatch_detail IS NULL OR char_length(dispatch_detail)<=4000))),
    CHECK (dispatch_status IS NULL OR dispatch_status IN ('blocked','unconfirmed')
        OR (dispatch_status='commandAccepted' AND dispatch_phase IS NOT NULL AND dispatch_phase='start')
        OR (dispatch_status='rejected' AND dispatch_phase IS NOT NULL)),
    CHECK (requested_delivery_id IS NULL OR (delivery_id IS NOT NULL AND requested_delivery_id=delivery_id)),
    CHECK ((cancelled_at IS NULL AND cancelled_by_run_id IS NULL AND cancelled_by_user_id IS NULL AND cancellation_reason IS NULL)
        OR (cancelled_at IS NOT NULL AND cancelled_by_user_id IS NOT NULL
            AND cancellation_reason IS NOT NULL AND btrim(cancellation_reason)<>'' AND char_length(cancellation_reason)<=4000)),
    CHECK ((retried_at IS NULL AND retried_by_run_id IS NULL AND retried_by_user_id IS NULL)
        OR (retried_at IS NOT NULL AND retried_by_user_id IS NOT NULL))
);
CREATE UNIQUE INDEX delivery_test_hooks_human_key ON public.delivery_test_hooks(project_slug,configured_by_user_id,idempotency_key)
    WHERE configured_by_run_id IS NULL;
CREATE INDEX delivery_test_hooks_source ON public.delivery_test_hooks(project_slug,source_run_id,commit_sha)
    WHERE hook_kind='delivery_test' AND delivery_id IS NULL AND cancelled_at IS NULL;
CREATE UNIQUE INDEX delivery_test_hooks_delivery_target ON public.delivery_test_hooks(project_slug,target_run_id)
    WHERE hook_kind='delivery_test';
CREATE UNIQUE INDEX delivery_test_hooks_completion_target ON public.delivery_test_hooks(project_slug,target_run_id)
    WHERE hook_kind='completion_program' AND cancelled_at IS NULL;
CREATE INDEX delivery_test_hooks_completion_source ON public.delivery_test_hooks(project_slug,source_task_slug,source_spec_id)
    WHERE hook_kind='completion_program' AND fact_id IS NULL AND cancelled_at IS NULL;
ALTER TABLE public.execution_events ADD COLUMN completion_context jsonb;
ALTER TABLE public.execution_events ADD COLUMN program_completion_basis jsonb CHECK (program_completion_basis IS NULL OR jsonb_typeof(program_completion_basis)='object');
ALTER TABLE public.manual_completions ADD COLUMN completion_context jsonb;

ALTER TABLE public.specs ADD COLUMN completion_generation bigint NOT NULL DEFAULT 0;
CREATE FUNCTION public.advance_completion_generation() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    NEW.completion_generation := OLD.completion_generation;
    IF NEW.stage IS DISTINCT FROM OLD.stage THEN
        NEW.completion_generation := OLD.completion_generation + 1;
    END IF;
    RETURN NEW;
END;
$$;
CREATE TRIGGER advance_completion_generation BEFORE UPDATE ON public.specs
    FOR EACH ROW EXECUTE FUNCTION public.advance_completion_generation();

CREATE TABLE public.summary_obligations (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    project_slug text NOT NULL REFERENCES public.projects(slug),
    goal_slug text NOT NULL,
    affected_slug text NOT NULL,
    actor_user_id text NOT NULL,
    actor_run_id text,
    idempotency_key text NOT NULL,
    record jsonb NOT NULL,
    applicability jsonb NOT NULL,
    FOREIGN KEY (project_slug,goal_slug) REFERENCES public.specs(project_slug,slug),
    FOREIGN KEY (project_slug,affected_slug) REFERENCES public.specs(project_slug,slug),
    FOREIGN KEY (project_slug,actor_run_id) REFERENCES public.run_bindings(project_slug,id),
    UNIQUE NULLS NOT DISTINCT (project_slug,actor_user_id,actor_run_id,idempotency_key)
);
CREATE INDEX summary_obligations_goal ON public.summary_obligations(project_slug,goal_slug,affected_slug,id DESC);

CREATE TABLE public.summary_acceptances (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    project_slug text NOT NULL REFERENCES public.projects(slug),
    goal_slug text NOT NULL,
    actor_user_id text NOT NULL,
    actor_run_id text,
    idempotency_key text NOT NULL,
    record jsonb NOT NULL,
    context jsonb NOT NULL,
    FOREIGN KEY (project_slug,goal_slug) REFERENCES public.specs(project_slug,slug),
    FOREIGN KEY (project_slug,actor_run_id) REFERENCES public.run_bindings(project_slug,id),
    UNIQUE NULLS NOT DISTINCT (project_slug,actor_user_id,actor_run_id,idempotency_key)
);
CREATE INDEX summary_acceptances_goal ON public.summary_acceptances(project_slug,goal_slug,id DESC);

CREATE TABLE public.composition_changes (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    project_slug text NOT NULL REFERENCES public.projects(slug),
    from_slug text NOT NULL,
    to_slug text NOT NULL,
    edge_type text NOT NULL CHECK (edge_type IN ('COMPOSES','DECIDED_IN')),
    operation text NOT NULL CHECK (operation IN ('INSERT','DELETE')),
    dispositions jsonb NOT NULL DEFAULT '[]'::jsonb,
    lost_obligations jsonb NOT NULL DEFAULT '[]'::jsonb,
    actor_user_id text,
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX composition_changes_project ON public.composition_changes(project_slug,id);
CREATE INDEX composition_changes_pair ON public.composition_changes(project_slug,from_slug,to_slug,edge_type,id DESC);

CREATE TABLE public.report_branch_flows (
    id text PRIMARY KEY,
    project_slug text NOT NULL REFERENCES public.projects(slug),
    configured_by text NOT NULL,
    idempotency_key text NOT NULL,
    definition jsonb NOT NULL,
    created_at timestamptz NOT NULL,
    cancelled_by text,
    cancel_reason text,
    cancelled_at timestamptz,
    UNIQUE (project_slug,id),
    UNIQUE (project_slug,configured_by,idempotency_key),
    CHECK ((cancelled_by IS NULL AND cancel_reason IS NULL AND cancelled_at IS NULL)
        OR (cancelled_by IS NOT NULL AND cancel_reason IS NOT NULL AND cancelled_at IS NOT NULL))
);

CREATE TABLE public.report_branch_members (
    project_slug text NOT NULL,
    flow_id text NOT NULL,
    run_id text NOT NULL,
    package_id text NOT NULL,
    condition_key text NOT NULL,
    when_value text NOT NULL CHECK (when_value IN ('true','false')),
    PRIMARY KEY (project_slug,run_id),
    FOREIGN KEY (project_slug,flow_id) REFERENCES public.report_branch_flows(project_slug,id),
    FOREIGN KEY (project_slug,run_id) REFERENCES public.run_bindings(project_slug,id),
    FOREIGN KEY (package_id) REFERENCES public.context_packages(id)
);
CREATE INDEX report_branch_members_flow ON public.report_branch_members(project_slug,flow_id);

CREATE TABLE public.report_branch_judgments (
    id text PRIMARY KEY,
    record_order bigint GENERATED ALWAYS AS IDENTITY UNIQUE,
    project_slug text NOT NULL,
    flow_id text NOT NULL,
    condition_key text NOT NULL,
    value text NOT NULL CHECK (value IN ('true','false','unknown')),
    input_refs jsonb NOT NULL,
    reason text NOT NULL,
    actor_user_id text NOT NULL,
    actor_run_id text,
    recorded_at timestamptz NOT NULL,
    predecessor_id text,
    UNIQUE (project_slug,id),
    UNIQUE NULLS NOT DISTINCT (project_slug,flow_id,condition_key,predecessor_id),
    FOREIGN KEY (project_slug,flow_id) REFERENCES public.report_branch_flows(project_slug,id),
    FOREIGN KEY (project_slug,predecessor_id) REFERENCES public.report_branch_judgments(project_slug,id)
);
CREATE INDEX report_branch_judgments_latest ON public.report_branch_judgments(project_slug,flow_id,condition_key,record_order DESC);

CREATE TABLE public.report_flow_joins (
    project_slug text NOT NULL,
    flow_id text NOT NULL,
    run_id text NOT NULL,
    package_id text NOT NULL,
    mode text NOT NULL CHECK (mode IN ('all','any')),
    allow_empty_skip boolean NOT NULL,
    configured_by text NOT NULL,
    configured_at timestamptz NOT NULL,
    PRIMARY KEY (project_slug,run_id),
    FOREIGN KEY (project_slug,flow_id) REFERENCES public.report_branch_flows(project_slug,id),
    FOREIGN KEY (project_slug,run_id) REFERENCES public.run_bindings(project_slug,id),
    FOREIGN KEY (package_id) REFERENCES public.context_packages(id)
);
CREATE INDEX report_flow_joins_flow ON public.report_flow_joins(project_slug,flow_id);
ALTER TABLE public.run_dispatches ADD COLUMN report_flow_basis jsonb;
ALTER TABLE public.run_dispatches ADD COLUMN report_join_basis jsonb;

CREATE TABLE public.candidate_loops (
    project_slug text NOT NULL,
    run_id text NOT NULL,
    task_slug text NOT NULL,
    package_id text NOT NULL,
    max_attempts integer NOT NULL CHECK (max_attempts > 0),
    plan_sources jsonb NOT NULL,
    termination_kind text NOT NULL DEFAULT 'report' CHECK (termination_kind IN ('report','satisfaction')),
    satisfaction_criterion text,
    join_mode text CHECK (join_mode IN ('all','any')),
    join_allow_empty_skip boolean,
    configured_by text NOT NULL,
    configured_at timestamptz NOT NULL,
    stop_actor_user_id text,
    stop_actor_run_id text,
    stop_reason text,
    stopped_at timestamptz,
    abandon_actor_user_id text,
    abandon_reason text,
    abandoned_at timestamptz,
    resolved_at timestamptz,
    completed_join jsonb,
    completed_condition jsonb,
    completed_satisfaction jsonb,
    PRIMARY KEY (project_slug,run_id),
    FOREIGN KEY (project_slug,run_id) REFERENCES public.run_bindings(project_slug,id),
    FOREIGN KEY (project_slug,task_slug) REFERENCES public.specs(project_slug,slug),
    FOREIGN KEY (package_id) REFERENCES public.context_packages(id),
    CHECK ((stopped_at IS NULL AND stop_actor_user_id IS NULL AND stop_actor_run_id IS NULL AND stop_reason IS NULL)
        OR (stopped_at IS NOT NULL AND stop_actor_user_id IS NOT NULL AND stop_reason IS NOT NULL)),
    CHECK ((abandoned_at IS NULL AND abandon_actor_user_id IS NULL AND abandon_reason IS NULL)
        OR (abandoned_at IS NOT NULL AND abandon_actor_user_id IS NOT NULL AND abandon_reason IS NOT NULL)),
    CHECK ((join_mode IS NULL AND join_allow_empty_skip IS NULL)
        OR (join_mode IS NOT NULL AND join_allow_empty_skip IS NOT NULL)),
    CHECK ((termination_kind='report' AND satisfaction_criterion IS NULL)
        OR (termination_kind='satisfaction' AND satisfaction_criterion IS NOT NULL
            AND btrim(satisfaction_criterion)<>'' AND char_length(satisfaction_criterion)<=4000))
);
CREATE UNIQUE INDEX candidate_loops_unresolved_task ON public.candidate_loops(project_slug,task_slug)
 WHERE resolved_at IS NULL AND abandoned_at IS NULL;

CREATE TABLE public.candidate_attempts (
    project_slug text NOT NULL,
    id text NOT NULL,
    run_id text NOT NULL,
    ordinal integer NOT NULL CHECK (ordinal > 0),
    predecessor_id text,
    consumed_condition jsonb,
    consumed_join jsonb,
    consumed_satisfaction jsonb,
    granted_at timestamptz NOT NULL,
    delivery_id text,
    flow_id text,
    PRIMARY KEY (project_slug,id),
    UNIQUE (project_slug,run_id,ordinal),
    UNIQUE (project_slug,predecessor_id),
    UNIQUE (project_slug,delivery_id),
    UNIQUE (project_slug,flow_id),
    FOREIGN KEY (project_slug,run_id) REFERENCES public.candidate_loops(project_slug,run_id),
    FOREIGN KEY (project_slug,predecessor_id) REFERENCES public.candidate_attempts(project_slug,id),
    FOREIGN KEY (delivery_id) REFERENCES public.deliveries(id),
    FOREIGN KEY (project_slug,flow_id) REFERENCES public.report_branch_flows(project_slug,id)
);
CREATE INDEX candidate_attempts_run ON public.candidate_attempts(project_slug,run_id,ordinal DESC);

CREATE TABLE public.candidate_satisfaction_judgments (
    id text PRIMARY KEY,
    event_order bigint GENERATED ALWAYS AS IDENTITY UNIQUE,
    project_slug text NOT NULL,
    run_id text NOT NULL,
    attempt_id text NOT NULL,
    delivery_id text NOT NULL REFERENCES public.deliveries(id),
    predecessor_id text REFERENCES public.candidate_satisfaction_judgments(id),
    value text NOT NULL CHECK (value IN ('true','false','unknown')),
    reason text NOT NULL CHECK (btrim(reason)<>'' AND char_length(reason)<=4000),
    actor_user_id text NOT NULL,
    actor_run_id text,
    recorded_at timestamptz NOT NULL,
    UNIQUE NULLS NOT DISTINCT (project_slug,attempt_id,predecessor_id),
    FOREIGN KEY (project_slug,run_id) REFERENCES public.candidate_loops(project_slug,run_id),
    FOREIGN KEY (project_slug,attempt_id) REFERENCES public.candidate_attempts(project_slug,id)
);
CREATE INDEX candidate_satisfaction_judgments_history ON public.candidate_satisfaction_judgments(project_slug,attempt_id,event_order DESC);

CREATE TABLE public.candidate_interventions (
    id text PRIMARY KEY,
    event_order bigint GENERATED ALWAYS AS IDENTITY UNIQUE,
    project_slug text NOT NULL,
    run_id text NOT NULL,
    attempt_id text NOT NULL,
    judgment_id text NOT NULL REFERENCES public.candidate_satisfaction_judgments(id),
    report_ids jsonb NOT NULL,
    conflict_kind text NOT NULL CHECK (conflict_kind IN ('passed_false','failed_true')),
    reason text NOT NULL,
    recorded_at timestamptz NOT NULL,
    resolved_at timestamptz,
    resolved_by_user_id text,
    resolution_reason text,
    resolution_judgment_id text REFERENCES public.candidate_satisfaction_judgments(id),
    resolution_report_ids jsonb,
    FOREIGN KEY (project_slug,run_id) REFERENCES public.candidate_loops(project_slug,run_id),
    FOREIGN KEY (project_slug,attempt_id) REFERENCES public.candidate_attempts(project_slug,id),
    CHECK ((resolved_at IS NULL AND resolved_by_user_id IS NULL AND resolution_reason IS NULL
        AND resolution_judgment_id IS NULL AND resolution_report_ids IS NULL)
        OR (resolved_at IS NOT NULL AND resolved_by_user_id IS NOT NULL AND resolution_reason IS NOT NULL
            AND resolution_judgment_id IS NOT NULL AND resolution_report_ids IS NOT NULL))
);
CREATE UNIQUE INDEX candidate_interventions_active ON public.candidate_interventions(project_slug,attempt_id) WHERE resolved_at IS NULL;
CREATE INDEX candidate_interventions_history ON public.candidate_interventions(project_slug,attempt_id,event_order DESC);

CREATE TABLE public.node_merges (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    project_slug text NOT NULL REFERENCES public.projects(slug),
    actor_user_id text NOT NULL,
    actor_run_id text,
    idempotency_key text NOT NULL,
    request jsonb NOT NULL,
    receipt jsonb NOT NULL,
    target_slug text NOT NULL,
    created_at timestamptz NOT NULL,
    UNIQUE NULLS NOT DISTINCT (project_slug,actor_user_id,actor_run_id,idempotency_key),
    FOREIGN KEY (project_slug,target_slug) REFERENCES public.specs(project_slug,slug),
    FOREIGN KEY (project_slug,actor_run_id) REFERENCES public.run_bindings(project_slug,id)
);
CREATE TABLE public.node_merge_sources (
    project_slug text NOT NULL,
    merge_id bigint NOT NULL REFERENCES public.node_merges(id),
    source_slug text NOT NULL,
    source_id text NOT NULL,
    before_version integer NOT NULL,
    after_version integer NOT NULL,
    PRIMARY KEY (project_slug,merge_id,source_slug),
    FOREIGN KEY (project_slug,source_slug) REFERENCES public.specs(project_slug,slug)
);
CREATE INDEX node_merge_sources_history ON public.node_merge_sources(project_slug,source_slug,merge_id DESC);
CREATE INDEX node_merges_target_history ON public.node_merges(project_slug,target_slug,id DESC);

-- Project bindings record the human-confirmed native project target of each
-- SpecGraph project. Revoked rows are retained history; at most one binding
-- per project is active at a time.
--

CREATE TABLE public.project_bindings (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    project_slug text NOT NULL REFERENCES public.projects(slug),
    environment_id text NOT NULL CHECK (btrim(environment_id) <> ''),
    native_project_id text NOT NULL CHECK (btrim(native_project_id) <> ''),
    workspace_root text,
    reason text NOT NULL CHECK (char_length(reason) BETWEEN 1 AND 4000),
    actor text NOT NULL CHECK (btrim(actor) <> ''),
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    revoked_at timestamp with time zone,
    revoke_reason text CHECK (revoke_reason IS NULL OR char_length(revoke_reason) BETWEEN 1 AND 4000),
    revoked_by text CHECK (revoked_by IS NULL OR btrim(revoked_by) <> '')
);

CREATE UNIQUE INDEX project_bindings_active ON public.project_bindings USING btree (project_slug) WHERE (revoked_at IS NULL);
CREATE INDEX project_bindings_history ON public.project_bindings USING btree (project_slug, id DESC);

-- Restore the migration connection's search path for Goose's version write.
RESET search_path;
-- +goose StatementEnd
